name: Setup Required Dependencies
description: "Setup all required dependencies for working with the source code"
inputs:
  github_token:
    description: "A Github PAT (e.g. secrets.GITHUB_TOKEN) with the required permissions"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ inputs.github_token }}
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: .config/global.json
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
