# To use this taskfile, please install from https://taskfile.dev/installation/
# List all available commands with `task --list-all`
version: "3"

tasks:
  build:
    desc: Build the source code (.NET) with packages cached
    cmds:
      - dotnet restore src/SoapOnAScope.sln
      - dotnet build src/SoapOnAScope.sln --no-restore

  build-cached:
    desc: Build the source code (.NET) with packages cached
    cmds:
      - dotnet restore src/SoapOnAScope.sln --locked-mode
      - dotnet build src/SoapOnAScope.sln --no-restore

  test:
    desc: Run all tests associated with the source code
    deps:
      - build
    cmds:
      - dotnet test src/SoapOnAScope.sln

  clean:
    desc: Clean the source code
    cmds:
      - dotnet clean src/SoapOnAScope.sln
      - task: build

  benchmark:
    desc: Generate the benchmarks
    deps:
      - build
    cmds:
      - dotnet run --project src/benchmarks/SoapOnAScope.Benchmarks/SoapOnAScope.Benchmarks.csproj

  pack:
    desc: Pack the source code into a NuGet package
    deps:
      - build
    cmds:
      - for: ["SoapOnAScope", "SoapOnAScope.Web"]
        cmd: dotnet pack src/lib/{{ .ITEM }}

  publish:
    desc: Publish the NuGet package to the NuGet repository
    deps:
      - pack
    vars:
      API_KEY: "Please provide your API key (API_KEY=abcd)"
    cmds:
      - dotnet nuget push .\artifacts\*.nupkg --api-key {{ .API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
